# Site settings
title: Nautilia
email: team@nautilia.co
url: https://nautilia.co
description: "Nautilia Computing"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#142b54'
  links: '#54a996'

# Footer settings
footer: Nautilia Computing

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: 
  - title: github
    url: https://github.com/nautilia-co

# Build settings
markdown: kramdown
permalink: pretty
